development:
	access_key_id: ACCESS_KEY_ID
	secret_access_key: SECRET_ACCESS_KEY

test:
	access_key_id: ACCESS_KEY_ID
	secret_access_key: SECRET_ACCESS_KEY

staging:
	access_key_id: ACCESS_KEY_ID
	secret_access_key: SECRET_ACCESS_KEY

production:
	access_key_id: ACCESS_KEY_ID
	secret_access_key: SECRET_ACCESS_KEY
