# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb48f95ebac33983dd7e5fd88e0b6045b57f416ead8bbac384502c5e9fba5a28403d5af0a0311e014760e60d65b803d06e381079756a46ae2f7452a41577aab

test:
  secret_key_base: 9df5696a81de63271e84ea3a59470a4346498dfb12a7f3aa2e53ac9499032eb5b00da305a23d5183cc110ff37f243af111023b2a99d9bb31c8093f3e65a6bfc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
